version: '3'
x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.0
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    PYTHONPATH: /opt/airflow # Add this line
  volumes:
    - ./:/opt/airflow
    
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: >
      bash -c "airflow db migrate &&
               airflow users create --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email airflow@example.com"

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    <<: *airflow-common
    command: scheduler

  mysql:
    image: mysql:8.0
    container_name: mysql_reviews
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviews_db
      MYSQL_USER: review_user
      MYSQL_PASSWORD: review_pass
    ports:
      - "3307:3306"  # host:container (host port changed to avoid 3306 conflict)
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_db:
  mysql_data: